config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :profiles

  resources :posts

  resources :groups do
    put:join, :on => :collection
  end

   resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

 def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation_path(conversation)
  end

  def index
    @conversations ||= current_user.mailbox.conversations.all
  end

  def reply
  	current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
  	redirect_to conversation_path(current_user)
  end

  def trashbin
    @trash ||= current_user.mailbox.trash.all
  end

  def trash
  	conversation.move_to_trash(current_user)
  	redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :back
   end

private

  def mailbox
	@mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
        when 0 then self
        when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt| %>
 <% message = receipt.message %>
 <%= message.sender.full_name %>
 
 < %= simple_format h message.body %>
 

app/views/conversations/_form.html.erb
<%= simple_form_for :conversation, url: :conversations do |f| %>
  <%= f.input :recipients %>
  <%= f.input :subject %>
  <%= f.input :body %>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
    <%= submit_tag 'Cancel', type: :reset, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/conversations/index.html.erb
<% if @conversations.empty? %>
no new messages 
<% else %>
<ul>
<%= @conversations.each do |conversation| %>
 <li>
    <%= link_to conversation.subject, conversation_path(conversation) %>
</li>
  <% end %>
</ul>
<% end %>
</br>
<%= link_to 'new conversation',  new_conversation_path %>

app/views/conversations/new.html.erb
<h1>Start Conversation</h1>
<%= render 'form' %>

app/views/conversations/show.html.erb
<h1>
  <%= conversation.subject %>
</h1>
<ul>
  <%= content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt| %>
    <% message = receipt.message %>
    <h3>
      <%= message.subject %>
    </h3>
    <p>
      <%= message.body %>
    </p>
  <% end %>
</ul>