config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :profiles

  resources :posts

  resources :groups do
    put:join, :on => :collection
  end

   resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_one :board, as: :boardable

	has_many :memberships
	has_many :users, through: :memberships 

	has_many :collaborations
	has_many :collaborators, through: :collaborations

	has_many :inverse_collaborations, :class_name =>  "Collaboration", :foreign_key => "collaborator_id"
	has_many :inverse_collaborators, :through => :inverse_collaborations, :source => :group
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  def join
    @group = Group.find(params[:id])
    @membership = Membership.new
    @membership.role = "follower"
    @membership.user = current_user
    @membership.group = @group
    @group.memberships << @membership
    redirect_to @group
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :type, :about, :details, :scope)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.select :group_type, %w[Project Commmunity Organization], {} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :about, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :about, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :details, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :scope, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.select :scope, %w[village town city state province country international idea] %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  groups_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/groups/_form_organization.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <%= f.hidden_field :group_type, :value => "Organization" %>
  <div class="form-group">
    <%= f.label :about, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :about, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :details, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :scope, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.select :scope, %w[domestic international observer] %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  groups_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => Group %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:about) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><%= model_class.human_attribute_name(:scope) %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.about %></td>
        <td><%= group.details %></td>
        <td><%= group.scope %></td>
        <td>
          <% if not group.users.include?(current_user) %>
          <%= link_to "Join", {:controller => :groups, :action => :join, id: @group.id}, :method => "put", :class => "btn btn-md btn-success" %>
        <% end %>
          <%= link_to "view", group_path(group), :class => "btn btn-md btn-default" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => @group.name %></h1>
</div>

<div class = "col-md-4">

     <pre class="prettyprint"><%= @group.name %></pre>
     <pre class="prettyprint"><%= @group.about %></pre>
     <pre class="prettyprint"><%= @group.details %></pre>
     <pre class="prettyprint"><%= @group.scope %></pre>

<div>



<div class="form-group">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_path(@group), :class => 'btn btn-default' %>
  <% if not @group.users.include?(current_user) %>
  <%= link_to "Join", {:controller => :groups, :action => :join, id: @group.id}, :method => "put", :class => "btn btn-lg btn-success" %>
  <% end %>
</div>